--DROP TABLE IF EXISTS _passport;
--
--CREATE TABLE _passport(
--    _person_id int PRIMARY KEY REFERENCES _person(_person_id)ON DELETE CASCADE,
--	_passport_number int NOT NULL
--);

--It's better
DROP TABLE IF EXISTS _passport;

CREATE TABLE _passport(
    _passport_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	_person_id int  UNIQUE REFERENCES _person(_person_id)ON DELETE CASCADE,
	_passport_number int NOT NULL
);