DROP TABLE IF EXISTS director;

CREATE TABLE director(
    director_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	director_name varchar(100)not null,
	director_age int CHECK(director_age>18)
);

INSERT INTO director(director_name,director_age)VALUES('Solmir',1002);
INSERT INTO director(director_name,director_age)VALUES('Almazir',43);

SELECT * FROM director LEFT JOIN actor ON director.director_id = actor.director_id;