DROP TABLE IF EXISTS actor_movie;
DROP TABLE IF EXISTS _actor;
DROP TABLE IF EXISTS movie;

CREATE TABLE _actor(
    _actor_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	_actor_name varchar(100)not null,
	_actor_age int CHECK(_actor_age>3)
);

CREATE TABLE movie(
    movie_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	movie_name varchar(100)not null
);
CREATE TABLE actor_movie(
    actor_id int REFERENCES _actor(_actor_id),
	movie_id int REFERENCES movie(movie_id),
	PRIMARY KEY(actor_id,movie_id)
);
SELECT * FROM _actor;
SELECT * FROM movie;